name: Fintec
favicon: null
layout_spectrum: 0.38054
typography_spectrum: 0.39008
title: Fintec Labs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.08727658982388675
  lightness: 0.455117478268221
  saturation: 0.6328360179904848
  rhythmicContrast: 0.009700363501906395
purpose: []
