name: Fintec
favicon: null
layout_spectrum: 0.31877
typography_spectrum: 0.39008
title: Fintec Labs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3b424a'
    - '#f5bc33'
    - '#1893aa'
    - '#95999c'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
